### ISSUE TITLE
Attribute Error?

### ISSUE THREAD

**Issue by SpaceSticks** [eth0izzle/bucket-stream#18]
Thanks in advance if you get time to reply. Im getting a attribute error;

[1m[33mWaiting for Certstream events - this could take a few minutes to queue up...[0mTraceback (most recent call last):

  File "C:\bucket-stream\bucket-stream.py", line 279, in <module>
    main()
  File "C:\bucket-stream\bucket-stream.py", line 271, in main
    signal.pause()  # pause the main thread
AttributeError: module 'signal' has no attribute 'pause'

Any thoughts?

**Comment by eth0izzle** [comment]
Are you in Windows?

**Comment by SpaceSticks** [comment]
Yes.

**Comment by eth0izzle** [comment]
Apparently signal.pause() isn’t implemented in Windows. I’ll push a fix soon
